#ifndef OPTIMIZATION_FLAGS_H
#define OPTIMIZATION_FLAGS_H

#define USE_THREAD_NAMES
#define TINYGPS_OPTION_NO_CUSTOM_FIELDS
#define PB_ENABLE_MALLOC 1

// RadioLib Exclusions
#define RADIOLIB_EXCLUDE_CC1101 1
#define RADIOLIB_EXCLUDE_NRF24 1
#define RADIOLIB_EXCLUDE_RF69 1
#define RADIOLIB_EXCLUDE_SX1231 1
#define RADIOLIB_EXCLUDE_SX1233 1
#define RADIOLIB_EXCLUDE_SI443X 1
#define RADIOLIB_EXCLUDE_RFM2X 1
#define RADIOLIB_EXCLUDE_AFSK 1
#define RADIOLIB_EXCLUDE_BELL 1
#define RADIOLIB_EXCLUDE_HELLSCHREIBER 1
#define RADIOLIB_EXCLUDE_MORSE 1
#define RADIOLIB_EXCLUDE_RTTY 1
#define RADIOLIB_EXCLUDE_SSTV 1
#define RADIOLIB_EXCLUDE_AX25 1
#define RADIOLIB_EXCLUDE_DIRECT_RECEIVE 1
#define RADIOLIB_EXCLUDE_PAGER 1
#define RADIOLIB_EXCLUDE_FSK4 1
#define RADIOLIB_EXCLUDE_APRS 1
#define RADIOLIB_EXCLUDE_LORAWAN 1

// Meshtastic Exclusions
#define MESHTASTIC_EXCLUDE_DROPZONE 1
#define MESHTASTIC_EXCLUDE_REMOTEHARDWARE 1
#define MESHTASTIC_EXCLUDE_HEALTH_TELEMETRY 1
#define MESHTASTIC_EXCLUDE_POWERSTRESS 1
#define MESHTASTIC_EXCLUDE_GENERIC_THREAD_MODULE 1

#define MAX_THREADS 40

#endif // OPTIMIZATION_FLAGS_H
