#ifndef OPTIMIZATION_FLAGS_H
#define OPTIMIZATION_FLAGS_H

// Global CrowdSense Terra Configuration
#define CROWD_SENSE_TERRA 1

// These are already defined in platformio.ini for some environments, 
// using #ifndef to prevent redefinition warnings.
#ifndef USE_THREAD_NAMES
#define USE_THREAD_NAMES
#endif

#ifndef TINYGPS_OPTION_NO_CUSTOM_FIELDS
#define TINYGPS_OPTION_NO_CUSTOM_FIELDS
#endif

#define PB_ENABLE_MALLOC 1

// RadioLib Exclusions
#define RADIOLIB_EXCLUDE_CC1101 1
#define RADIOLIB_EXCLUDE_NRF24 1
#define RADIOLIB_EXCLUDE_RF69 1
#define RADIOLIB_EXCLUDE_SX1231 1
#define RADIOLIB_EXCLUDE_SX1233 1
#define RADIOLIB_EXCLUDE_SI443X 1
#define RADIOLIB_EXCLUDE_RFM2X 1
#define RADIOLIB_EXCLUDE_AFSK 1
#define RADIOLIB_EXCLUDE_BELL 1
#define RADIOLIB_EXCLUDE_HELLSCHREIBER 1
#define RADIOLIB_EXCLUDE_MORSE 1
#define RADIOLIB_EXCLUDE_RTTY 1
#define RADIOLIB_EXCLUDE_SSTV 1
#define RADIOLIB_EXCLUDE_AX25 1
#define RADIOLIB_EXCLUDE_DIRECT_RECEIVE 1
#define RADIOLIB_EXCLUDE_PAGER 1
#define RADIOLIB_EXCLUDE_FSK4 1
#define RADIOLIB_EXCLUDE_APRS 1
#define RADIOLIB_EXCLUDE_LORAWAN 1

// Meshtastic Exclusions
#define MESHTASTIC_EXCLUDE_HEALTH_TELEMETRY 0 // Keep for INA219 if needed

#ifdef CROWD_SENSE_TERRA
// AUTHORITATIVE EXCLUSION LIST FOR GROUND SENSE TERRA
// If it's not explicitly ENABLED in platformio.ini, it MUST be excluded here.

#ifndef ENABLE_BME280
#define MESHTASTIC_EXCLUDE_BME280 1
#endif

#ifndef ENABLE_LTR390
#define MESHTASTIC_EXCLUDE_LTR390 1
#endif

#ifndef ENABLE_VEML7700
#define MESHTASTIC_EXCLUDE_VEML7700 1
#endif

#ifndef ENABLE_INA219
#define MESHTASTIC_EXCLUDE_INA219 1
#endif

// Strictly exclude all others
#define MESHTASTIC_EXCLUDE_BMP280 1
#define MESHTASTIC_EXCLUDE_BMP085 1
#define MESHTASTIC_EXCLUDE_BMP3XX 1
#ifndef ENABLE_BME680
#define MESHTASTIC_EXCLUDE_BME680 1
#endif
#define MESHTASTIC_EXCLUDE_MCP9808 1
#define MESHTASTIC_EXCLUDE_SHTC3 1
#define MESHTASTIC_EXCLUDE_LPS22 1
#define MESHTASTIC_EXCLUDE_SHT3X 1
#define MESHTASTIC_EXCLUDE_SHT4X 1
#define MESHTASTIC_EXCLUDE_AHT10 1
#define MESHTASTIC_EXCLUDE_QMC5883L 1
#define MESHTASTIC_EXCLUDE_QMC6310 1
#define MESHTASTIC_EXCLUDE_INA260 1
#define MESHTASTIC_EXCLUDE_INA3221 1
#define MESHTASTIC_EXCLUDE_MAX17048 1
#define MESHTASTIC_EXCLUDE_PM25 1
#define MESHTASTIC_EXCLUDE_TSL2591 1
#define MESHTASTIC_EXCLUDE_MLX90614 1
#define MESHTASTIC_EXCLUDE_MLX90632 1
#define MESHTASTIC_EXCLUDE_RCWL9620 1
#define MESHTASTIC_EXCLUDE_NAU7802 1
#define MESHTASTIC_EXCLUDE_OPT3001 1
#define MESHTASTIC_EXCLUDE_AHT10 1
#define MESHTASTIC_EXCLUDE_BH1750 1
#define MESHTASTIC_EXCLUDE_MAX30102 1
#define MESHTASTIC_EXCLUDE_RAK12035 1
#define MESHTASTIC_EXCLUDE_INDICATOR 1
#define MESHTASTIC_EXCLUDE_CGRADSENS 1
#define MESHTASTIC_EXCLUDE_DROPZONE 1

// Motion Sensor Exclusions
#define MESHTASTIC_EXCLUDE_LSM6DS3 1
#define MESHTASTIC_EXCLUDE_ICM20948 1
#define MESHTASTIC_EXCLUDE_BMM150 1
#define MESHTASTIC_EXCLUDE_BMX160 1
#define MESHTASTIC_EXCLUDE_MPU6050 0 // KEEP
#define MESHTASTIC_EXCLUDE_LIS3DH 0  // KEEP

#endif

// System Settings
#define MAX_THREADS 40

#endif // OPTIMIZATION_FLAGS_H

